name: Ghost Development server

on:
  push:
    branches:
    - main

jobs:
  build:
    # using Ubuntu
    runs-on: ubuntu-latest

    steps:
      - run: php artisan key:generate
      - run: composer install
      - run: php artisan migrate
      - run: php artisan serve
      - run: sudo service apache2 restart

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST:  3.14.79.41
          USERNAME: ubuntu
          PORT:  22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          #source: "./dist"
          target: "/var/www/html/"
          strip_components: 2  
